### ISSUE TITLE
Publish / build

### ISSUE THREAD

**Issue by dariusFromShire** [ruidfigueiredo/electron-cgi#2]
Can you provide any documentation or guidance on distributing apps created with electron-cgi. How to publish this app with .net code?

**Comment by ruidfigueiredo** [comment]
You can use electron-packager (or electron-builder, although I haven't tested it) to package your app.
The thing you have to be aware of is that the path you use in the ConnectionBuilder will change when the app is packaged.

So, if your dotnet app is next to main.js in a folder named DotNetApp, after you package your app with electron-packager the generated executable will be in a folder with a resources folder that inside will have an app folder that inside will have DotNetApp. (resources/app/DotNetApp)

Since this is predictable you can, for example, rely on environment variables to have ConnectionBuilder use one path at development time and another when the app is packaged.

**Comment by Dobutamine** [comment]
Thanks for the quick reply, i really appreciate this but i still can't get it to work. I changed to path to the dotnet app. So my dotnet app is called dotnet-bridge and it is located in a folder called src. I changed the connection builder command to this
const connection = new ConnectionBuilder().connectTo("dotnet", "run", "--project", "resources/app/src/dotnet-bridge").build();

That error i get when executing the package (build with electron-packager) = Uncaught Exception:
Error: Could not start dotnet. Are you sure you have the right path?

Any ideas?

**Comment by ruidfigueiredo** [comment]
I tried it just now and this is what I got:

![image](https://user-images.githubusercontent.com/1956584/74111940-6cbe3500-4b90-11ea-8640-b400e4ac554f.png)

Run this:

`npx electron-packager . tim_antonious_app --platform=linux --arch=x64`

and dotnet-bridge ends up in tim_antonious_app-linux-x64/resources/app/dotnet-brigde, as highlighted:

```
.
├── dotnet-bridge
	...
├── index.html
├── LICENSE.md
├── main.js
├── node_modules
	...
├── package.json
├── package-lock.json
├── preload.js
├── README.md
├── renderer.js
└── tim_antonious_app-linux-x64
	....
    ├── resources
    │   └── app
    │       ├── dotnet-bridge <-----------------
    		.....
    │       ├── index.html
    │       ├── LICENSE.md
    │       ├── main.js
    │       ├── node_modules
    │       │   ├── @electron
    │       │   ├── @sindresorhus
    │       │   ├── @szmarczak
    │       │   └── @types
    │       ├── package.json
    │       ├── package-lock.json
    │       ├── preload.js
    │       ├── README.md
    │       └── renderer.js
    ├── resources.pak
    ├── snapshot_blob.bin
    ├── swiftshader
    │   ├── libEGL.so
    │   └── libGLESv2.so
    ├── tim_antonious_app
    ├── v8_context_snapshot.bin
    ├── version
    └── vk_swiftshader_icd.json
```

Also, you should use dotnet publish in your dotnet app so that you get an executable and don't have to rely on `dotnet run` when you are ready to publish: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21

**Comment by Dobutamine** [comment]
Thx a million. It alk works fine now. ElectronCGI is great and solves a major cross platform problem for me.

Tim

Verstuurd vanaf mijn iPhone

Op 10 feb. 2020 om 00:18 heeft Rui Figueiredo <notifications@github.com> het volgende geschreven:

﻿

I tried it just now and this is what I got:

[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1956584%2F74111940-6cbe3500-4b90-11ea-8640-b400e4ac554f.png&data=02%7C01%7C%7C866de056b49946dd35a608d7adb66b64%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637168871299352417&sdata=Ja7RfP%2BKberWbyf3zwNPrGK99vQNIfFfwS9jJQpfvuU%3D&reserved=0>

Run this:

npx electron-packager . tim_antonious_app --platform=linux --arch=x64

and dotnet-bridge ends up in tim_antonious_app-linux-x64/resources/app/dotnet-brigde, as highlighted:

.
├── dotnet-bridge
        ...
├── index.html
├── LICENSE.md
├── main.js
├── node_modules
        ...
├── package.json
├── package-lock.json
├── preload.js
├── README.md
├── renderer.js
└── tim_antonious_app-linux-x64
        ....
    ├── resources
    │   └── app
    │       ├── dotnet-bridge <-----------------
                .....
    │       ├── index.html
    │       ├── LICENSE.md
    │       ├── main.js
    │       ├── node_modules
    │       │   ├── @electron
    │       │   ├── @sindresorhus
    │       │   ├── @szmarczak
    │       │   └── @types
    │       ├── package.json
    │       ├── package-lock.json
    │       ├── preload.js
    │       ├── README.md
    │       └── renderer.js
    ├── resources.pak
    ├── snapshot_blob.bin
    ├── swiftshader
    │   ├── libEGL.so
    │   └── libGLESv2.so
    ├── tim_antonious_app
    ├── v8_context_snapshot.bin
    ├── version
    └── vk_swiftshader_icd.json


Also, you should use dotnet publish in your dotnet app so that you get an executable and don't have to rely on dotnet run when you are ready to publish: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdotnet%2Fcore%2Ftools%2Fdotnet-publish%3Ftabs%3Dnetcore21&data=02%7C01%7C%7C866de056b49946dd35a608d7adb66b64%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637168871299362405&sdata=zAdMQSTy7EtmUCvykvp6cSukLBD1I9UCVyMDOxIM73s%3D&reserved=0>
