### ISSUE TITLE
Error handling issue and .net framework app

### ISSUE THREAD

**Issue by knight-dev** [ruidfigueiredo/electron-cgi#22]
Firstly, let me thank @ruidfigueiredo for not just coming up with this idea but implementing it. I find it to be an excellent alternative to electron.net, neutronium etc. since I want to keep the vue ui code separate from the c# but still be able to interact with each other on demand.

That said, I'm having two issues:

1) Any data sent from .net is being interpreted as an error.
Please see code comments below:

connection.send('greeting', 'John', (error, theGreeting) => {
    if (error) {
        console.log(error); // always triggered..even when no error
        return;
    }

    console.log(theGreeting); // never gets called
});

2) This is not an error but more a question. As it relates to the file location in the connection builder arguments, how exactly is it referencing the .exe? What folder is it searching and which directory is the root?
I find that the code below works fine for .net core apps but not .net framework apps. I suspect it's related to the difference in folder structure. 

const connection = new ConnectionBuilder()
        .connectTo('dotnet', 'run', '--project', 'DotNetConsoleProjectWithElectronCgiDotNetNugetPackage')
        .build();

Btw, I'm currently using this approach, which works but I don't have the benefit of .net watcher: 
const connection = new ConnectionBuilder()
        .connectTo('C:/folder/DotNetConsoleProjectWithElectronCgiDotNetNugetPackage.exe')
        .build();

These issues are in the context of a vue app built with vuetify, electron-nuxt, vuex and a .net framework 4.7.2 console app built in visual studio 2019. Latest version of electron-cgi used in both cases.

Thanks, in advance for your assistance. I'm not an expert in c# or javascript but I know a thing or two and I'm willing to contribute where I can.

**Comment by ruidfigueiredo** [comment]
Hi @knight-dev 

Regarding your first question, do you mind sharing what error are you getting?
If I had to hazard a guess I'd say you are not using the latest version of ElectronCgi.DotNet and you are getting the result as the first parameter. Latest nuget package is `1.0.3` and latest npm package is `1.0.6` (old versions of electron-cgi did not adhere to the common way callbacks are used in node, where the first parameter is an error object. Instead, old versions had the result as the first parameter).

Regarding your second question the working directory is node's so that typically is the folder you start electron from, usually using `npm start`. Also, you can specify a full path for the `--project` parameter (this is valid: `dotnet run --project /home/knight-dev/Project/FolderWhereCsprojIsIn`)

If you are unsure what is your working directory, in node you can do this:

`console.log(process.cwd())`

And that should print your current working directory.

If you don't have access to the console for whatever reason you can always do this as a quick and easy way to get things logged to a file:

`require('fs').writeFile(pathToFile, whatYouWantToLog, {flag:'a'}); //the flag=a means append, file will be created if it does not exist`

**Comment by knight-dev** [comment]
Thank you for your quick response. Your suggestions have been really helpful. I perhaps needed to be a little clearer about the error issue. Basically, the error and result variable order was reversed due to the old version. 0.0.5 node version..c# was up to date. As it relates to the .net framework project not running. It seems the real issue is that the project created in vs2019 won't run using dotnet cli..possibly due to the csproj configuration or that the cli only works for .net core apps.

**Comment by ruidfigueiredo** [comment]
Hi @knight-dev 

You should be able to create a .net core project in VS 2019 and that should work with the dotnet cli. Newer of .NET core versions getting closer and closer to feature parity with the .NET Framework.

Otherwise you'll "connectTo" the exe file.
