### ISSUE TITLE
Everytime when try to connect, get "Connection to dotnet was terminated (code: 0)" immediately and disconnect

### ISSUE THREAD

**Issue by KiloZak** [ruidfigueiredo/electron-cgi#23]
Hi @ruidfigueiredo, thank for your great work. I'm new to electron. Trying to develop a combination with electron , angular and C#. I'm facing a issue everytime when electron run code below. I get "null", "lost", "Connection to dotnet was terminated (code: 0)" on my console log. And of course, there is no connections between electon & c# console. electron-cgi.log is created but the content is empty. 
Any idea, why this issue happen? Any help would be greatful!

Electron side:
```javascript
const { ConnectionBuilder } = require("electron-cgi");

  let connection = new ConnectionBuilder()
  .connectTo("dotnet", "run", "--project", "./core")
  .build();

connection.onDisconnect = () => {
  console.log("lost");
};

connection.send("greeting", "Jack", (response: any) => {
  console.log(response);
  connection.close();
});
```
C# console side:
```javascript
static void Main(string[] args)
{
    var connection = new ConnectionBuilder()
    .WithLogging()
    .Build();

    connection.On<string, string>("greeting", name => "Hello " + name);

    connection.Listen();
}
```

**Comment by ruidfigueiredo** [comment]
Hey @KiloZak 

The first argument for the send callback is the error (if any). That's why you see null, that's the error value (no error). Just change this line:

`connection.send("greeting", "Jack", (response: any) => {`

To:

`connection.send("greeting", "Jack", (err: any, response: any) => {`

And you'll see the message arriving successfully.

Also you can turn on trace logging (you'd be able to see the messages that were exchanged between node and dotnet in electroncgi.log this way): `var connection = new ConnectionBuilder().WithLogging(minimumLogLevel: Microsoft.Extensions.Logging.LogLevel.Trace).Build();`

Sometimes this helps to debug instances when something is off.

**Comment by KiloZak** [comment]
You just save my day!
